# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitequestionchoice',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='choice',
            name='codes',
            field=models.ManyToManyField(to='search.Code'),
        ),
    ]
