# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160415_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='section',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Section Name'),
        ),
    ]
