# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20170320_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioncategory',
            name='name',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
