# Generated by Django 2.0.4 on 2018-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20170427_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequestion',
            name='validation',
            field=models.TextField(blank=True, help_text='Text validation entered here', null=True, verbose_name='Validation'),
        ),
    ]
