# Generated by Django 2.0.4 on 2018-05-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_sitequestion_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQuestionArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('text', models.TextField(db_index=True, null=True, verbose_name='Text')),
                ('type', models.CharField(choices=[('integer', 'Integer'), ('text', 'Text'), ('checkbox', 'Checkbox'), ('yesno', 'Yes/No'), ('dropdown', 'Dropdown'), ('date_mdy', 'Date: MM/DD/YYYY'), ('date_dmy', 'Date: DD/MM/YYYY'), ('date_ymd', 'Date: YYYYY/MM/DD'), ('datetime_mdy', 'Datetime: MM/DD/YYYY HH:MM'), ('datetime_dmy', 'Datetime: DD/MM/YYYY HH:MM'), ('datetime_ymd', 'Datetime: YYYY/MM/DD HH:MM'), ('datetime_seconds_mdy', 'Datetime with seconds: MM/DD/YYYY HH:MM:SS'), ('datetime_seconds_dmy', 'Datetime with seconds: DD/MM/YYYY HH:MM:SS'), ('datetime_seconds_ymd', 'Datetime with seconds: YYYY/MM/DD HH:MM:SS'), ('email', 'Email'), ('alpha_only', 'Letters Only'), ('mrn_10d', 'MRN (10 digits)'), ('number', 'Number'), ('number_1dp', 'Number with 1 Decimal Place'), ('number_2dp', 'Number with 2 Decimal Place'), ('number_3dp', 'Number with 3 Decimal Place'), ('number_4dp', 'Number with 4 Decimal Place'), ('phone_australia', 'Phone - Australia'), ('phone', 'Phone'), ('postalcode_australia', 'Postal Code - Australia'), ('postalcode_canada', 'Postal Code - Canada'), ('ssn', 'Social Security Number - U.S.'), ('time', 'Time: HH:MM'), ('time_mm_ss', 'Time: MM:SS'), ('vmrn', 'Vanderbilt MRN'), ('zipcode', 'Zipcode - U.S.'), ('truefalse', 'True/False'), ('notes', 'Note'), ('description', 'Descipriton'), ('sql', 'SQL Field'), ('radio', 'Radio Button'), ('calc', 'Calculated Field'), ('matrix', 'Matrix'), ('descriptive', 'Descriptive')], db_index=True, max_length=24, null=True, verbose_name='Type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('calculation', models.TextField(blank=True, help_text='If this field is a result of a calculation, enter it here', null=True, verbose_name='Calculation')),
                ('min_val', models.FloatField(blank=True, help_text='The minimum value a user can enter for this field, if applicable.', null=True, verbose_name='Minimun Value')),
                ('max_val', models.FloatField(blank=True, help_text='The maximum value a user can enter for this field, if applicable.', null=True, verbose_name='Maximum Value')),
                ('validation', models.TextField(blank=True, help_text='Text validation entered here', null=True, verbose_name='Validation')),
                ('ordering', models.IntegerField(null=True, verbose_name='Ordering')),
                ('align', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alignment')),
                ('matrix_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrix Name')),
                ('unknown_val', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unknown Value')),
                ('branching_logic', models.TextField(blank=True, null=True, verbose_name='Branching Logic')),
                ('date_archived', models.DateTimeField()),
            ],
            options={
                'db_table': 'search_site_questions_archive',
            },
        ),
        migrations.CreateModel(
            name='SiteQuestionArchiveChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(verbose_name='Ordering')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Choice')),
                ('site_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_choices', to='search.SiteQuestionArchive')),
            ],
            options={
                'db_table': 'search_site_question_archive_choices',
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='sitequestionarchive',
            name='choices',
            field=models.ManyToManyField(through='search.SiteQuestionArchiveChoice', to='search.Choice'),
        ),
        migrations.AddField(
            model_name='sitequestionarchive',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_archive', to='search.Form'),
        ),
        migrations.AddField(
            model_name='sitequestionarchive',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_questions_archive', to='search.Question'),
        ),
        migrations.AddField(
            model_name='sitequestionarchive',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_archive', to='search.Site'),
        ),
        migrations.AddField(
            model_name='sitequestionarchive',
            name='tags',
            field=models.ManyToManyField(to='search.Tag'),
        ),
    ]
