# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(max_length=25),
        ),
    ]
