# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170320_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewversion',
            name='revision',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
